version: '3.1'
services:
  mongo:
    image: mongo
    privileged: true
    ports:
      - "27017:27017"
    volumes:
      - v_mongo:/data/db
  mongo-client:
    build: .
    depends_on:
      - "mongo"
    environment:
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=training
    # entrypoint: tail -f /etc/hosts

volumes:
  v_mongo:
